- name: add influx repo key
  raw: curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -

- name: add influx apt repository
  apt_repository:
    repo: 'deb https://repos.influxdata.com/ubuntu bionic stable'
    state: present
    filename: influx
    #update_cache: yes
