- name: install telegraf
  ignore_errors: yes # todo richtig machen!!
  apt:
    name: telegraf
    state: present
    update_cache: yes

- name: set telegraf interval to 1s
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: agent
    option: interval
    value: '"1s"'
  register: telegraf_conf
  ignore_errors: yes # todo

- name: Set telegraf output adress
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: '[outputs.influxdb]'
    option: urls
    value: '["http://192.168.42.2:8086"]'
  register: telegraf_conf
  ignore_errors: yes # todo

- name: start telegraf
  ignore_errors: yes # todo
  service:
    name: telegraf
    state: started
    enabled: yes

- name: restart telegraf
  ignore_errors: yes #todo
  service:
    name: telegraf
    state: restarted
  when: telegraf_conf.changed
