# vim:ft=yaml

- hosts: sa2
  gather_facts: False
  become: true

  pre_tasks:
    - name: Bootstrap
      include_tasks: subtasks/bootstrap.yml

  tasks:
    - name: add influxDB apt repo
      include_tasks: subtasks/influx_repo.yml

    - name: setup telegraf
      include_tasks: subtasks/telegraf_setup.yml

    - name: install packages
      apt:
        pkg:
          - ruby
          - rsyslog

    #arch wiki ftw https://wiki.archlinux.org/index.php/Network_bridge
    - name: Enable ip forwarding
      raw: sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"

    - name: make interfaces promisc
      raw: ip link set {{ item }} promisc on
      with_items:
        - enp0s9
        - enp0s10

    - name: create bridge
      raw: sh -c "ip link add name br0 type bridge | true"

    - name: set bridge up
      raw: ip link set br0 up

    - name: add interfaces to bridge
      raw: ip link set {{ item }} master br0
      with_items:
        - enp0s9
        - enp0s10

    - name: Load br_netfilter kernel module
      modprobe:
        name: br_netfilter
        state: present


    - name: Install pip3
      apt:
        name: python3-pip
        state: present

    - name: install pip packages
      pip:
        name:
          - flask
          - requests
          - netifaces
          - PyJWT

- name: Setup wrapper
  hosts: sa2
  gather_facts: False
  become: false

  tasks:
    - name: clone repo
      git:
        repo: git@gitlab2.informatik.uni-wuerzburg.de:descartes/nfv-security/SecurityApplianceWrapper.git
        dest: SecurityApplianceWrapper
        accept_hostkey: yes

    - name: copy config
      copy:
        src: firewallwrapper.ini
        dest: wrapper.ini
      # Start wrapper

- name: Setup Firewall
  hosts: sa2
  gather_facts: False
  become: false

  tasks:
    - name: clone repo
      git:
        repo: git@gitlab2.informatik.uni-wuerzburg.de:descartes/nfv-security/FireGuardian.git
        dest: FireGuardian
        accept_hostkey: yes

    - name: install filewatcher
      gem:
        name: filewatcher
        state: present

    - name: install concurrent-ruby
      gem:
        name: concurrent-ruby
        state: present

    # sudo ruby firewall.rb
