# vim:ft=yaml

- hosts: sa1
  gather_facts: False
  become: true

  pre_tasks:
    - name: Bootstrap
      include_tasks: subtasks/bootstrap.yml

  tasks:
    - name: add influxDB apt repo
      include_tasks: subtasks/influx_repo.yml

    - name: setup telegraf
      include_tasks: subtasks/telegraf_setup.yml

    #FIXME fails to install non-interactively
    #- name: install snort
      #apt:
        #name: snort

    - name: make interfaces promisc
      raw: ip link set "{{ item }}" promisc on
      with_items:
        - enp0s9
        - enp0s10
