# vim:ft=yaml

- hosts: sa1
  gather_facts: False
  become: true

  pre_tasks:
    - name: Bootstrap
      include_tasks: subtasks/bootstrap.yml

  tasks:
    - name: add influxDB apt repo
      include_tasks: subtasks/influx_repo.yml

    - name: setup telegraf
      include_tasks: subtasks/telegraf_setup.yml

    #FIXME fails to install non-interactively
    - name: install snort
      ignore_errors: true
      apt:
        name: snort

    - name: make interfaces promisc
      raw: ip link set "{{ item }}" promisc on
      with_items:
        - enp0s9
        - enp0s10

- name: Setup wrapper
  hosts: sa1
  gather_facts: False
  become: false

  tasks:
    - name: clone repo
      git:
        repo: git@gitlab2.informatik.uni-wuerzburg.de:descartes/nfv-security/SecurityApplianceWrapper.git
        dest: SecurityApplianceWrapper
        accept_hostkey: yes

    - name: copy config
      copy:
        src: ids/wrapper.ini
        dest: wrapper.ini
      # Start wrapper

- name: Setup snort parser
  hosts: sa1
  gather_facts: False
  become: false

  tasks:
  - name: Copy snort helper
    copy:
      src: ids/snort.py
      dest: snort.py

  - name: Copy snort parser
    copy:
      src: ids/readsnort.py
      dest: readsnort.py

  # sudo python3 readsnort.py
  # start snort
