# vim:ft=yaml

- hosts: masters
  gather_facts: False
  become: true

  pre_tasks:
    - name: Bootstrap
      include_tasks: subtasks/bootstrap.yml

  tasks:
    - name: add influxDB apt repo
      include_tasks: subtasks/influx_repo.yml

    - name: setup telegraf
      include_tasks: subtasks/telegraf_setup.yml

    - name: install influx server
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - influxdb
        - chronograf

    - name: Set telegraf output adress
      ini_file:
        path: /etc/influxdb/influxdb.conf
        section: 'http'
        option: bind-address
        value: '"192.168.42.2:8086"'
      register: influx_conf


    - name: setup services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - influxdb
        - chronograf

    - name: restart influx if reconfigured
      service:
        name: influxdb
        state: restarted
      when: influx_conf.changed

    - name: install pip3
      apt:
        name: python3-pip

    - name: install ryu
      pip:
        name:
          - ryu
          - flask
          - PyJWT
          - numpy

    # todo only jar
    - name: create directory l7sdntest jar
      file:
        path: /home/vagrant/l7sdntest
        state: directory

    - name: create directory l7sdntest bin
      file:
        path: /home/vagrant/l7sdntestBin
        state: directory

    - name: copy l7sdntest.jar
      copy:
        src: subtasks/l7sdntest/l7sdntest.jar
        dest: /home/vagrant/l7sdntest
        mode: '0777'

    #- name: copy l7sdntest bin
      #copy:
        #src: subtasks/l7sdntest/bin
        #dest: /home/vagrant/l7sdntestBin
        #mode: '0777'

    - name: copyl7sdntest Configuration XML file
      copy:
        src: subtasks/l7sdntest/aTest
        dest: /home/vagrant/l7sdntest
        mode: '0777'



