# vim:ft=yaml

- hosts: all
  become: true
  vars_files:
    - vars_files/telegraf.yml

  roles:
    - role: influxdb
#      influxdb_bind_hostname: "{{ ansible_hostname }}"
    - role: telegraf
    - role: chronograf
