# vim:ft=yaml

- hosts: masters
  gather_facts: False
  become: true
  vars:
    java_rpm: jdk-14.0.1_linux-x64_bin.rpm

  pre_tasks:
    - name: Bootstrap
      include_tasks: subtasks/bootstrap.yml

  tasks:
    #- name: Update and upgrade apt packages
      #apt:
        #upgrade: yes
        #update_cache: yes
        #cache_valid_time: 86400  # One day

    - name: add influxDB apt repo
      include_tasks: subtasks/influx_repo.yml

    - name: setup telegraf
      include_tasks: subtasks/telegraf_setup.yml

    - name: install influx server
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - influxdb
        - chronograf

    - name: Set telegraf output adress
      ini_file:
        path: /etc/influxdb/influxdb.conf
        section: 'http'
        option: bind-address
        value: '"192.168.42.2:8086"'
      register: influx_conf


    - name: setup services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - influxdb
        - chronograf

    - name: restart influx if reconfigured
      service:
        name: influxdb
        state: restarted
      when: influx_conf.changed

    - name: install pip3
      apt:
        name:
          - python3-pip

    - name: install ryu
      pip:
        name:
          - ryu
          - flask
          - PyJWT
          - numpy

    - name: Update Apt Cache
      become: true
      apt:
        update_cache: yes


# todo task "Setup l7sdntest" in roles oder mit playbook auslagern (nur diese)
- name: Setup l7sdntest
  become: true
  hosts: masters
  gather_facts: false

  tasks:
    - name: Update Apt Cache
      become: true
      apt:
        update_cache: yes

    - name: Install OpenJDK Java Java 11
      become: yes
      apt:
        name: openjdk-11-jdk
        state: present

    - name: create directory l7sdntest jar
      file:
        path: /home/vagrant/l7sdntest
        state: directory

    - name: copy l7sdntest.jar
      copy:
        src: subtasks/l7sdntest/l7sdntest.jar
        dest: /home/vagrant/l7sdntest
        mode: '0777'

- name: Setup l7sdntest for Master
  become: true
  hosts: masters
  gather_facts: false

  tasks:
    - name: Copy all Config Files
      copy: src=subtasks/l7sdntest/configs/{{ item }} dest=/home/vagrant/l7sdntest
      with_items:
        - Jonathan_MA_easy
        - aTest
