# vim:ft=yaml

- name: bootstrap, repos
  hosts: all
  become: true

  tasks:
    - name: Bootstrap
      include_tasks: subtasks/bootstrap.yml

- name: Copy git ssh key
  hosts: all
  become: false
  tasks:
  - name: Copy private key
    copy:
      src: gitkey
      dest: .ssh/id_rsa
      mode: 0600
  - name: Copy public key
    copy:
      src: gitkey.pub
      dest: .ssh/id_rsa.pub

- name: setup dhcp-server
  gather_facts: False
  hosts: masters
  become: true
  vars:
    dhcp_server: true

  tasks:
    - name: install isc-dhcp-server
      apt:
        name: isc-dhcp-server
        state: present
      when: dhcp_server

    - name: copy dhcp-config
      copy:
        src: subtasks/dhcp/dhcpd.conf
        dest: /etc/dhcp/dhcpd.conf
        mode: '0644'
        owner: root
        group: root
      when: dhcp_server

    - name: copy dhcp-defaults
      copy:
        src: subtasks/dhcp/defaults
        dest: /etc/default/isc-dhcp-server
        mode: '0644'
        owner: root
        group: root
      when: dhcp_server

    - name: start dhcp server
      service:
        name: isc-dhcp-server
        state: restarted
        enabled: yes
      when: dhcp_server

- name: setup apt-server
  gather_facts: False
  hosts: masters
  vars:
    apt_server: false
  become: true

  tasks:
    - name: install apt-mirror, apache
      apt:
        name:
          - apt-mirror
          - apache2
        state: present
        update_cache: yes
      when: apt_server

    - name: copy apt-mirror list
      copy:
        src: subtasks/apt-mirror/mirror.list
        dest: /etc/apt/mirror.list
        mode: '0644'
        owner: root
        group: root
      when: apt_server

    - name: sync apt-mirror
      shell: apt-mirror
      when: apt_server

    - name: symbolic link for ubuntu
      file:
        src: /var/spool/apt-mirror/mirror/archive.ubuntu.com/ubuntu/
        dest: /var/www/html/ubuntu
        owner: www-data
        group: www-data
        state: link
      when: apt_server

    - name: symbolic link for influx
      file:
        src: /var/spool/apt-mirror/mirror/repos.influxdata.com/ubuntu/
        dest: /var/www/html/influx
        owner: www-data
        group: www-data
        state: link
      when: apt_server

    - name: run apache
      service:
        name: apache2
        state: started
        enabled: yes
      when: apt_server

- name: setup apt-clients
  gather_facts: False
  hosts: all
  become: true
  vars:
    apt_server: false

  tasks:
    - name: remove default debs
      apt_repository:
        repo: "{{ item }}"
        state: absent
      with_items:
        - deb http://de.archive.ubuntu.com/ubuntu bionic main restricted
        - deb http://de.archive.ubuntu.com/ubuntu bionic-security main restricted
        - deb http://de.archive.ubuntu.com/ubuntu bionic-updates restricted
        - deb-src http://de.archive.ubuntu.com/ubuntu bionic main restricted
        - deb-src http://de.archive.ubuntu.com/ubuntu bionic-security main restricted
        - deb-src http://de.archive.ubuntu.com/ubuntu bionic-updates restricted
      when: apt_server

    - name: add new deps
      apt_repository:
        repo: "{{ item }}"
        state: present
      with_items:
        - deb http://192.168.206.1/ubuntu bionic main restricted
        - deb http://192.168.206.1/ubuntu bionic-security main restricted
        - deb http://192.168.206.1/ubuntu bionic-updates restricted
        - deb-src http://192.168.206.1/ubuntu bionic main restricted
        - deb-src http://192.168.206.1/ubuntu bionic-security main restricted
        - deb-src http://192.168.206.1/ubuntu bionic-updates restricted
      when: apt_server

- name: setup influxdb, chronograf @ master
  gather_facts: False
  hosts: masters
  become: true

  tasks:
    - name: add influxDB apt repo
      include_tasks: subtasks/influx_repo.yml

    - name: install influx server
      apt:
        name:
          - influxdb
          - chronograf
        state: present
        update_cache: yes

    - name: Set telegraf output adress
      ini_file:
        path: /etc/influxdb/influxdb.conf
        section: 'http'
        option: bind-address
        value: '"192.168.206.1:8086"'
      register: influx_conf

    - name: setup services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - influxdb
        - chronograf

    - name: restart influx if reconfigured
      service:
        name: influxdb
        state: restarted
      when: influx_conf.changed

- name: setup telegraf
  hosts: all
  gather_facts: False
  become: true

  tasks:
    - name: add influxDB apt repo
      include_tasks: subtasks/influx_repo.yml
    
    - name: setup telegraf
      include_tasks: subtasks/telegraf_setup.yml
