# vim:ft=yaml

- hosts: switches
  gather_facts: False
  become: true

  pre_tasks:
    - name: Bootstrap
      include_tasks: subtasks/bootstrap.yml

  tasks:
    - name: add influxDB apt repo
      include_tasks: subtasks/influx_repo.yml

    - name: setup telegraf
      include_tasks: subtasks/telegraf_setup.yml

    - name: install OVS
      apt:
        name: openvswitch-switch
        state: present
        update_cache: yes

    - name: setup bridge
      openvswitch_bridge:
        bridge: br0

    - name: setup bridge ports
      openvswitch_port:
        bridge: br0
        port: "{{ item }}"
        state: present
      with_items:
        - enp0s9
        - enp0s10
        - enp0s16
        - enp0s17
        - enp0s18
        - enp0s19
        - enp2s0
        - enp2s1
        - enp2s2

    - name: bringing interfaces up
      raw: ip link set "{{ item }}" up
      with_items:
        - enp0s9
        - enp0s10
        - enp0s16
        - enp0s17
        - enp0s18
        - enp0s19
        - enp2s0
        - enp2s1
        - enp2s2

    - name: bringing interfaces up
      raw: ip link set "{{ item }}" up
      with_items:
        - enp0s9
        - enp0s10
        - enp0s16
        - enp0s17
        - enp0s18
        - enp0s19
        - enp2s0
        - enp2s1
        - enp2s2
